# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Site Information
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # Customize typed.js
  # https://github.com/mattboldt/typed.js/#customization
  typed_option:
  # source 调用第三方服务
  # false 关闭调用
  # 1  调用一言网的一句话（简体） https://hitokoto.cn/
  # 2  调用一句网（简体） http://yijuzhan.com/
  # 3  调用今日诗词（简体） https://www.jinrishici.com/
  # subtitle 会先显示 source , 再显示 sub 的内容
  source: 3
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:

# 页面布局
index_layout: 3

tag_img: "/images/bg1.png" # 首页顶部图片
index_img: "/images/bg2.jpg" # 文章页顶部图片

# Avatar
avatar:
  img: /images/avatar.jpg # 头像图片
  effect: false # 头像效果

# Favicon
favicon: /images/ico.ico

# Social links
social:
  fas fa-envelope: mailto:wyd0617@qq.com || 邮箱
  fab fa-github: https://github.com/wyd1520866381 || Github || "#hdhfbb"

# Footer Custom Text
# custom_text: 由 Hexo 强力驱动 & Butterfly 主题设计。<br> wyd1520866381.github.io

# 菜单设置
menu:
  首页: / || fas fa-home
  项目: /projects/ || fas fa-project-diagram
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  # 归档: /archives/ || fas fa-archive
  关于我: /about/ || fas fa-user
  # 在线体验||fas fa-list:
  #   推金币: /coins/index.html || fas fa-music

error_404:
  enable: true
  subtitle: "页面没有找到"
  background:

# 加载动画 Loading Animation
preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  source: 2
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url: /styles/minimal.css

series:
  enable: true
  orderBy: "date" # Order by title or date
  order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
  number: true

footer:
  owner:
    # 是否启用所有者显示
    enable: true
    # 网站创建年份
    since: 2025
  # 自定义文本
  custom_text: "<a href='https://beian.miit.gov.cn' target='_blank'>辽ICP备2025057989号-1</a>"
  # 主题和框架的版权声明
  copyright: false

aside:
  enable: true
  position: left
  card_author:
    enable: true
    description: "你好，我是Edon Wang(王艺栋)，一名充满热情的开发者，在前端、WebGL、元宇宙和AR/VR领域有多年经验。欢迎来到我的博客！"
    button:
      enable: true
      icon: fas fa-envelope
      text: 联系我
      link: mailto:wyd0617@qq.com
  card_announcement:
    enable: true
    title: 联系方式
    content: "WeChat: wyd1520866381<br>QQ: 1520866381"
  card_webinfo:
    enable: false
  card_post_series:
    # 是否显示系列文章卡片
    enable: true
    # 标题显示系列名称
    series_title: false
    # 排序方式：title 或 date
    orderBy: "date"
    # 排序顺序：1 表示升序，-1 表示降序
    order: -1

copy:
  enable: true
  # Add the copyright information after copied content
  copyright:
    enable: true
    limit_count: 150

theme_color:
  enable: true
  main: "#3498db"
  paginator: "#bdc3c7"
  button_hover: "#e0e0e0"
  text_selection: "#3498db"
  link_color: "#007aff"
  meta_color: "#7f8c8d"
  hr_color: "#ecf0f1"
  code_foreground: "#333333"
  code_background: "rgba(236, 240, 241, .5)"
  toc_color: "#3498db"
  blockquote_padding_color: "#bdc3c7"
  blockquote_background_color: "rgba(189, 195, 199, .2)"
  scrollbar_color: "#bdc3c7"
  meta_theme_color_light: "ffffff"
  meta_theme_color_dark: "#1a1a1a"

# Add a mask to the header and footer
mask:
  header: true
  footer: true

# 封面设置
cover:
  # 是否禁用封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 主页封面的位置
  # 选择: left/right/both
  position: both
  # 当未设置封面时，显示默认封面
  default_cover:
    - /images/default-cover.png

index_top_img_height: 44rem

default_top_img: linear-gradient(to right, #00c6ff, #0072ff)
